name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always
  ENV RUSTFLAGS: "-Dwarnings"
  ENV RUSTDOCFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        rustup update
        rustup target add thumbv7em-none-eabihf
    - name: Lint
      run: |
        cargo fmt --check
        cargo clippy --release
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
